title: Computational and Molecular Pathology
author: Vignesh Shanmugam, MD
email: vshanmug@broadinstitute.org
description: > # this means to ignore newlines until "baseurl:"
Pathologist and scientist trying to make sense of things
# social links
twitter_username: Vignesh_Shan # DO NOT include the @ character, or else the build will fail!
github_username:  vigneshshanmug # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
